# Generated by Django 6.0.7 on 2026-07-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DASHBOARD", "Dashboard"),
                            ("ENROLLMENT_TRENDS", "Enrollment Trends"),
                            ("STUDENT_GROWTH", "Student Growth"),
                            ("REVENUE_SUMMARY", "Revenue Summary"),
                            ("ATTENDANCE", "Attendance"),
                            ("ASSIGNMENT_COMPLETION", "Assignment Completion"),
                            ("CERTIFICATES", "Certificates"),
                            ("TEACHER_PERFORMANCE", "Teacher Performance"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        max_length=40,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Query parameters / filters used to generate this report.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved report",
                "verbose_name_plural": "saved reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="analytics_s_report__5d6822_idx",
                    )
                ],
            },
        ),
    ]
