# Generated by Django 6.0.7 on 2026-07-19 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("enrolled_count", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("class_start_time", models.TimeField(blank=True, null=True)),
                ("class_end_time", models.TimeField(blank=True, null=True)),
                (
                    "working_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of weekday integers (0=Mon … 6=Sun) or day names.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=50)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Online / hybrid meeting URL."
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "batch",
                "verbose_name_plural": "batches",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="BatchSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("is_cancelled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "batch schedule",
                "verbose_name_plural": "batch schedules",
                "ordering": ["batch", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BatchStudent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "batch student",
                "verbose_name_plural": "batch students",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. MORNING, DAYTIME, EVENING, WEEKEND, or custom code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "working_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of weekday integers (0=Mon … 6=Sun) or day names.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "shift",
                "verbose_name_plural": "shifts",
                "ordering": ["start_time", "name"],
            },
        ),
    ]
