# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="batchschedule",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="batches.batch",
            ),
        ),
        migrations.AddField(
            model_name="batchstudent",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_students",
                to="batches.batch",
            ),
        ),
        migrations.AddField(
            model_name="batchstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_memberships",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="batches.shift",
            ),
        ),
        migrations.AddIndex(
            model_name="batchschedule",
            index=models.Index(
                fields=["batch", "day_of_week"], name="batches_bat_batch_i_4e0109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchstudent",
            index=models.Index(
                fields=["batch", "status"], name="batches_bat_batch_i_299e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchstudent",
            index=models.Index(
                fields=["student", "status"], name="batches_bat_student_5e3bef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batchstudent",
            constraint=models.UniqueConstraint(
                fields=("batch", "student"), name="unique_batch_student"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["course", "status"], name="batches_bat_course__9cc24a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["teacher", "status"], name="batches_bat_teacher_956ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["code"], name="batches_bat_code_9c254b_idx"),
        ),
    ]
