# Generated by Django 6.0.7 on 2026-07-19 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0002_initial"),
        ("courses", "0002_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchschedule",
            options={
                "ordering": ["day_of_week", "start_time"],
                "verbose_name": "batch schedule",
                "verbose_name_plural": "batch schedules",
            },
        ),
        migrations.RemoveIndex(
            model_name="batch",
            name="batches_bat_course__9cc24a_idx",
        ),
        migrations.RemoveIndex(
            model_name="batch",
            name="batches_bat_teacher_956ca1_idx",
        ),
        migrations.RemoveIndex(
            model_name="batch",
            name="batches_bat_code_9c254b_idx",
        ),
        migrations.RemoveIndex(
            model_name="batchschedule",
            name="batches_bat_batch_i_4e0109_idx",
        ),
        migrations.RemoveIndex(
            model_name="batchstudent",
            name="batches_bat_batch_i_299e3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="batchstudent",
            name="batches_bat_student_5e3bef_idx",
        ),
        migrations.AlterField(
            model_name="batch",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="batch",
            name="working_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="batchstudent",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DROPPED", "Dropped"),
                    ("COMPLETED", "Completed"),
                    ("SUSPENDED", "Suspended"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="working_days",
            field=models.JSONField(
                blank=True, default=list, help_text="List of weekday names or indices."
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["status", "code"], name="batches_bat_status_d671c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["start_date"], name="batches_bat_start_d_8ca549_idx"
            ),
        ),
    ]
