# Generated by Django 6.0.7 on 2026-07-19 13:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0003_initial"),
        ("courses", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="batches.batch",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taken_by_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance session",
                "verbose_name_plural": "attendance sessions",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "date"], name="attendance__batch_i_4cdc5d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyAttendanceSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("present_days", models.PositiveIntegerField(default=0)),
                ("absent_days", models.PositiveIntegerField(default=0)),
                ("late_days", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_attendance_summaries",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_attendance_summaries",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "monthly attendance summary",
                "verbose_name_plural": "monthly attendance summaries",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="attendance__year_c0374a_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("student__isnull", False), ("teacher__isnull", True)
                            ),
                            models.Q(
                                ("student__isnull", True), ("teacher__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="summary_requires_student_xor_teacher",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("student__isnull", False)),
                        fields=("student", "month", "year"),
                        name="unique_student_month_year_summary",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("teacher__isnull", False)),
                        fields=("teacher", "month", "year"),
                        name="unique_teacher_month_year_summary",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        db_index=True,
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("session_start", models.TimeField(blank=True, null=True)),
                ("session_end", models.TimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance",
                        to="batches.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_attendance",
                        to="courses.course",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_student_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student attendance",
                "verbose_name_plural": "student attendance",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "date"], name="attendance__batch_i_ab544b_idx"
                    ),
                    models.Index(
                        fields=["student", "date"],
                        name="attendance__student_0335ea_idx",
                    ),
                    models.Index(
                        fields=["status", "date"], name="attendance__status_1860e7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "batch", "date"),
                        name="unique_student_batch_date_attendance",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("ON_LEAVE", "On Leave"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        db_index=True,
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_teacher_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher attendance",
                "verbose_name_plural": "teacher attendance",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "date"],
                        name="attendance__teacher_e4f8f3_idx",
                    ),
                    models.Index(
                        fields=["status", "date"], name="attendance__status_3675d1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "date"),
                        name="unique_teacher_date_attendance",
                    )
                ],
            },
        ),
    ]
