# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("designation", models.CharField(blank=True, max_length=150)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "specialization",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specialization areas.",
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("linkedin_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("CV", "CV / Resume"),
                            ("CERTIFICATE", "Certificate"),
                            ("CONTRACT", "Contract"),
                            ("ID_PROOF", "ID Proof"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="teachers/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher document",
                "verbose_name_plural": "teacher documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherExperience",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("organization", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=150)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher experience",
                "verbose_name_plural": "teacher experiences",
                "ordering": ["-is_current", "-from_date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherQualification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("field", models.CharField(blank=True, max_length=150)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="teachers/qualifications/"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher qualification",
                "verbose_name_plural": "teacher qualifications",
                "ordering": ["-year", "degree"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_schedules",
                        to="batches.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_schedules",
                        to="courses.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher schedule",
                "verbose_name_plural": "teacher schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherWorkload",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "hours_assigned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "hours_completed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workloads",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher workload",
                "verbose_name_plural": "teacher workloads",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["status", "teacher_id"], name="teachers_te_status_3082f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["department"], name="teachers_te_departm_3b845d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherworkload",
            constraint=models.UniqueConstraint(
                fields=("teacher", "month", "year"),
                name="unique_teacher_workload_month_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherworkload",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="teacher_workload_month_range",
            ),
        ),
    ]
