# Generated by Django 6.0.7 on 2026-07-29 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_notification_uuids(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    for row in Notification.objects.filter(uuid__isnull=True).iterator():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered or authored this notification (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Fine-grained event key, e.g. ASSIGNMENT_CREATED.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("READ", "Read"),
                    ("FAILED", "Failed"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(gen_notification_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="browser_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_daily",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_weekly",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-App"),
                    ("EMAIL", "Email"),
                    ("BROWSER", "Browser"),
                    ("SMS", "SMS"),
                    ("PUSH", "Push"),
                ],
                db_index=True,
                default="IN_APP",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ENROLLMENT", "Enrollment"),
                    ("ASSIGNMENT", "Assignment"),
                    ("PAYMENT", "Payment"),
                    ("CERTIFICATE", "Certificate"),
                    ("ATTENDANCE", "Attendance"),
                    ("ANNOUNCEMENT", "Announcement"),
                    ("SYSTEM", "System"),
                    ("ADMIN", "Admin"),
                    ("AUTH", "Authentication"),
                    ("STUDENT", "Student"),
                    ("COURSE", "Course"),
                    ("BATCH", "Batch"),
                    ("EXAM", "Exam"),
                    ("SECURITY", "Security"),
                ],
                db_index=True,
                default="SYSTEM",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critical"),
                    ("HIGH", "High"),
                    ("MEDIUM", "Medium"),
                    ("LOW", "Low"),
                ],
                db_index=True,
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per notification_type toggles, e.g. {"ASSIGNMENT": {"email": true, "in_app": true, "browser": true}}',
            ),
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("BROWSER", "Browser"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification delivery",
                "verbose_name_plural": "notification deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("ARCHIVED", "Archived"),
                            ("DELETED", "Deleted"),
                            ("FAILED", "Failed"),
                            ("RETRIED", "Retried"),
                            ("PREFERENCE_SKIPPED", "Skipped by preference"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification log",
                "verbose_name_plural": "notification logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("BROWSER", "Browser"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        default="IN_APP",
                        max_length=20,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT", "Enrollment"),
                            ("ASSIGNMENT", "Assignment"),
                            ("PAYMENT", "Payment"),
                            ("CERTIFICATE", "Certificate"),
                            ("ATTENDANCE", "Attendance"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("SYSTEM", "System"),
                            ("ADMIN", "Admin"),
                            ("AUTH", "Authentication"),
                            ("STUDENT", "Student"),
                            ("COURSE", "Course"),
                            ("BATCH", "Batch"),
                            ("EXAM", "Exam"),
                            ("SECURITY", "Security"),
                        ],
                        default="SYSTEM",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("title_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
                "ordering": ["code", "channel"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("code", "channel"),
                        name="uniq_active_template_code_channel",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_archived", "-created_at"],
                name="notificatio_recipie_2c5a1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "-created_at"], name="notificatio_status_37b3f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event_code", "-created_at"],
                name="notificatio_event_c_230517_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "status", "-created_at"],
                name="notificatio_priorit_869082_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel", "status", "-created_at"],
                name="notificatio_channel_0eda49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification", "channel"],
                name="notificatio_notific_7707f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["action", "-created_at"], name="notificatio_action_9a8c50_idx"
            ),
        ),
    ]
