# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated total duration of this chapter in minutes.",
                    ),
                ),
            ],
            options={
                "verbose_name": "chapter",
                "verbose_name_plural": "chapters",
                "ordering": ["course", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "chapter progress",
                "verbose_name_plural": "chapter progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_parts", models.PositiveIntegerField(default=0)),
                ("total_parts", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "course progress",
                "verbose_name_plural": "course progress",
                "ordering": ["-last_accessed_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("NOTES", "Notes"),
                            ("PDF", "PDF"),
                            ("RESOURCE", "Resource"),
                            ("MIXED", "Mixed"),
                        ],
                        db_index=True,
                        default="MIXED",
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("video_duration_seconds", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="If true, content is visible without enrollment.",
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "part",
                "verbose_name_plural": "parts",
                "ordering": ["chapter", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="content/attachments/%Y/%m/")),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "part attachment",
                "verbose_name_plural": "part attachments",
                "ordering": ["part", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOC", "Document"),
                            ("LINK", "Link"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="content/resources/%Y/%m/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "part resource",
                "verbose_name_plural": "part resources",
                "ordering": ["part", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "student progress",
                "verbose_name_plural": "student progress",
                "ordering": ["-updated_at"],
            },
        ),
    ]
