# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="chapterprogress",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_progress",
                to="content.chapter",
            ),
        ),
        migrations.AddField(
            model_name="chapterprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_progress",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="courseprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="content.chapter",
            ),
        ),
        migrations.AddField(
            model_name="partattachment",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="content.part",
            ),
        ),
        migrations.AddField(
            model_name="partresource",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="content.part",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="content.chapter",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="content.part",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_progress",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["course", "is_published"], name="content_cha_course__8736e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["course", "order"], name="content_cha_course__b72972_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_chapter_slug_per_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapterprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "chapter"), name="unique_student_chapter_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["student", "status"], name="content_cou_student_4c4e82_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["chapter", "is_published"],
                name="content_par_chapter_643c0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["chapter", "order"], name="content_par_chapter_2e1f5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["content_type"], name="content_par_content_1d084d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("chapter", "slug"), name="unique_part_slug_per_chapter"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprogress",
            index=models.Index(
                fields=["student", "course"], name="content_stu_student_ffc387_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprogress",
            index=models.Index(
                fields=["student", "status"], name="content_stu_student_c83a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprogress",
            index=models.Index(
                fields=["course", "status"], name="content_stu_course__819d16_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "part"), name="unique_student_part_progress"
            ),
        ),
    ]
