# Generated by Django 6.0.6 on 2026-08-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_chapter",
                to="content.part",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="content/videos/%Y/%m/"
            ),
        ),
        migrations.CreateModel(
            name="VideoPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.PositiveIntegerField(default=0)),
                ("end_time", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_parts",
                        to="content.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "video part",
                "verbose_name_plural": "video parts",
                "ordering": ["video", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "order"), name="unique_video_part_order"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="video_part_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("order__gte", 1)),
                        name="video_part_order_positive",
                    ),
                ],
            },
        ),
    ]
