# Generated by Django 6.0.6 on 2026-08-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_partresource_resource_type_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="partresource",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Video duration in seconds. Used to validate timestamps when > 0.",
            ),
        ),
        migrations.CreateModel(
            name="VideoTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "time_seconds",
                    models.PositiveIntegerField(
                        help_text="Offset from the start of the video, in seconds."
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Optional display order. Listing is primarily by time_seconds.",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamps",
                        to="content.partresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "video timestamp",
                "verbose_name_plural": "video timestamps",
                "ordering": ["resource", "time_seconds", "id"],
                "indexes": [
                    models.Index(
                        fields=["resource", "time_seconds"],
                        name="content_vid_resourc_d245e3_idx",
                    )
                ],
            },
        ),
    ]
