# Generated by Django 6.0.6 on 2026-08-16 05:09

import apps.common.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_videotimestamp_and_resource_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="partresource",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="partresource",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="Uncompressed original upload retained for retry/audit.",
                null=True,
                upload_to="content/resources/%Y/%m/original/",
            ),
        ),
        migrations.AddField(
            model_name="partresource",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "Uploading"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="ready",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="content/videos/%Y/%m/",
                validators=[
                    apps.common.file_validators.FileExtensionTypeValidator(
                        ["mp4", "mov", "mkv", "webm", "m4v"]
                    ),
                    apps.common.file_validators.FileSizeValidator(209715200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="partresource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Playable file (compressed video when processing completes).",
                null=True,
                upload_to="content/resources/%Y/%m/",
            ),
        ),
    ]
