# Generated by Django 6.0.6 on 2026-08-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_topic"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="topic",
            new_name="content_top_part_id_eed18e_idx",
            old_name="content_top_part_id_order_idx",
        ),
    ]
