# Generated by Django 6.0.6 on 2026-08-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_classschedule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="classschedule",
            new_name="content_cla_course__b008ee_idx",
            old_name="content_cla_course__date_idx",
        ),
        migrations.RenameIndex(
            model_name="classschedule",
            new_name="content_cla_course__ada7dd_idx",
            old_name="content_cla_course__pub_idx",
        ),
    ]
