# Generated by Django 6.0.6 on 2026-08-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_coursefaq"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coursefaq",
            new_name="content_cou_course__ad781a_idx",
            old_name="content_cou_course__order_idx",
        ),
    ]
