/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as DashboardBatchesRouteImport } from './routes/dashboard/batches'
import { Route as DashboardBlogRouteImport } from './routes/dashboard/blog'
import { Route as DashboardCareersRouteImport } from './routes/dashboard/careers'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as DashboardContentRouteImport } from './routes/dashboard/content'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardFeesRouteImport } from './routes/dashboard/fees'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard/gallery'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardPartnersRouteImport } from './routes/dashboard/partners'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard/resources'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardSeoRouteImport } from './routes/dashboard/seo'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardShiftsRouteImport } from './routes/dashboard/shifts'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard/students'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardTeachersRouteImport } from './routes/dashboard/teachers'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBatchesRoute = DashboardBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogRoute = DashboardBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPartnersRoute = DashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/change-password'
    | '/login'
    | '/auth/callback'
    | '/dashboard/assignments'
    | '/dashboard/batches'
    | '/dashboard/blog'
    | '/dashboard/careers'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/content'
    | '/dashboard/courses'
    | '/dashboard/events'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/shifts'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teachers'
    | '/dashboard/testimonials'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/auth/callback'
    | '/dashboard/assignments'
    | '/dashboard/batches'
    | '/dashboard/blog'
    | '/dashboard/careers'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/content'
    | '/dashboard/courses'
    | '/dashboard/events'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/shifts'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teachers'
    | '/dashboard/testimonials'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/change-password'
    | '/login'
    | '/auth/callback'
    | '/dashboard/assignments'
    | '/dashboard/batches'
    | '/dashboard/blog'
    | '/dashboard/careers'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/content'
    | '/dashboard/courses'
    | '/dashboard/events'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/shifts'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teachers'
    | '/dashboard/testimonials'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/batches': {
      id: '/dashboard/batches'
      path: '/batches'
      fullPath: '/dashboard/batches'
      preLoaderRoute: typeof DashboardBatchesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog': {
      id: '/dashboard/blog'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardBlogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/partners': {
      id: '/dashboard/partners'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shifts': {
      id: '/dashboard/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teachers': {
      id: '/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardBatchesRoute: typeof DashboardBatchesRoute
  DashboardBlogRoute: typeof DashboardBlogRoute
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPartnersRoute: typeof DashboardPartnersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShiftsRoute: typeof DashboardShiftsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardTeachersRoute: typeof DashboardTeachersRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardBatchesRoute: DashboardBatchesRoute,
  DashboardBlogRoute: DashboardBlogRoute,
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPartnersRoute: DashboardPartnersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShiftsRoute: DashboardShiftsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
