# Generated by Django 6.0.7 on 2026-07-19 11:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="cms/gallery/")),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "gallery item",
                "verbose_name_plural": "gallery items",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("content", models.TextField(blank=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("ABOUT", "About"),
                            ("CONTACT", "Contact"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/pages/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("site_name", models.CharField(default="ShikshaLab", max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cms/site/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="cms/site/"),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("footer_text", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "site setting",
                "verbose_name_plural": "site settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(blank=True, max_length=150)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="cms/testimonials/"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "testimonial",
                "verbose_name_plural": "testimonials",
                "ordering": ["order", "-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("STUDENTS", "Students"),
                            ("TEACHERS", "Teachers"),
                            ("ADMIN", "Admin"),
                        ],
                        db_index=True,
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "audience", "priority"],
                        name="cms_announc_is_publ_2a706a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("image", models.ImageField(upload_to="cms/banners/")),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cms/banners/mobile/"
                    ),
                ),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("ABOUT", "About"),
                            ("COURSES", "Courses"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="HOME",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["placement", "is_active", "order"],
                        name="cms_banner_placeme_530342_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                            ("REMOTE", "Remote"),
                        ],
                        db_index=True,
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "career",
                "verbose_name_plural": "careers",
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_published", "-posted_at"],
                        name="cms_career_is_acti_03668e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="cms_contact_is_read_e62a9d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/events/"),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("registration_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "start_datetime"],
                        name="cms_event_is_publ_4c5912_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/blog/"),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "blog post",
                "verbose_name_plural": "blog posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "-published_at"],
                        name="cms_blogpos_is_publ_ab0fa1_idx",
                    ),
                    models.Index(
                        fields=["category"], name="cms_blogpos_categor_db6ae3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CMSTeacherHighlight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("blurb", models.CharField(blank=True, max_length=500)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_highlights",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS teacher highlight",
                "verbose_name_plural": "CMS teacher highlights",
                "ordering": ["order", "-is_featured"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher",), name="unique_cms_teacher_highlight"
                    )
                ],
            },
        ),
    ]
