# Generated by Django 6.0.7 on 2026-07-24 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_coursereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("details_emailed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "event registration",
                "verbose_name_plural": "event registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="coursereview",
            new_name="cms_courser_status_e54018_idx",
            old_name="cms_coursereview_status_idx",
        ),
        migrations.RenameIndex(
            model_name="coursereview",
            new_name="cms_courser_course__62ce68_idx",
            old_name="cms_coursereview_course_idx",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="cms.event",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["status", "-created_at"], name="cms_eventre_status_db76df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="cms_eventre_event_i_d13b5d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("event", "email"),
                name="uniq_active_event_registration_email",
            ),
        ),
    ]
