# Generated by Django 6.0.6 on 2026-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_sitesetting_google_search_console_verification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactmessage",
            new_name="cms_contact_status_34aaa4_idx",
            old_name="cms_contact_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="galleryitem",
            new_name="cms_gallery_is_publ_78672b_idx",
            old_name="cms_gallery_is_publ_8e6b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="galleryitem",
            new_name="cms_gallery_event_i_689786_idx",
            old_name="cms_gallery_event_i_4c9f1d_idx",
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="features_eyebrow",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="features_heading",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_name",
            field=models.CharField(default="skillsikshya", max_length=200),
        ),
    ]
