# Generated by Django 6.0.7 on 2026-07-19 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0003_initial"),
        ("courses", "0002_initial"),
        ("enrollments", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "html_template",
                    models.TextField(
                        help_text="HTML body with placeholders for certificate fields."
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/templates/headers/",
                    ),
                ),
                ("footer_text", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means a global template.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_templates",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate template",
                "verbose_name_plural": "certificate templates",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "verification_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/qr/"
                    ),
                ),
                ("issue_date", models.DateField()),
                ("completion_date", models.DateField()),
                (
                    "grade_or_score",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/pdf/"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="batches.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="students.student",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="certificates.certificatetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateVerificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="certificates.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate verification log",
                "verbose_name_plural": "certificate verification logs",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.AddIndex(
            model_name="certificatetemplate",
            index=models.Index(
                fields=["is_active", "is_default"],
                name="certificate_is_acti_c718d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["student", "status"], name="certificate_student_16729a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["course", "status"], name="certificate_course__221588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["status", "issue_date"], name="certificate_status_0b60da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificateverificationlog",
            index=models.Index(
                fields=["certificate", "-verified_at"],
                name="certificate_certifi_04a6f2_idx",
            ),
        ),
    ]
