# Generated by Django 6.0.6 on 2026-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_module_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatetemplate",
            name="design_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Field positions, typography, and layout metadata for dynamic rendering.",
            ),
        ),
    ]
