# Generated by Django 6.0.7 on 2026-07-20 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="Optional remote avatar URL when no uploaded file is set.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Headline shown on the profile card.",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi")],
                        default="en",
                        max_length=8,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("compact_sidebar", models.BooleanField(default=False)),
                ("marketing_emails", models.BooleanField(default=False)),
                ("digest_weekly", models.BooleanField(default=True)),
                ("assignment_alerts", models.BooleanField(default=True)),
                ("fee_reminders", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settings",
            },
        ),
    ]
