# Generated by Django 6.0.7 on 2026-07-29 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_provisional_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Email or phone as submitted (normalized).",
                        max_length=255,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS")],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OTP_SENT", "OTP Sent"),
                            ("VERIFIED", "Verified"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                            ("LOCKED", "Locked"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset request",
                "verbose_name_plural": "password reset requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetAudit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("OTP_SENT", "OTP Sent"),
                            ("OTP_RESENT", "OTP Resent"),
                            ("OTP_FAILED", "OTP Failed"),
                            ("OTP_VERIFIED", "OTP Verified"),
                            ("LOCKED", "Locked"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("TOKEN_ISSUED", "Token Issued"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_reset_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reset_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to="accounts.passwordresetrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset audit",
                "verbose_name_plural": "password reset audits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("EXPIRED", "Expired"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to="accounts.passwordresetrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP verification",
                "verbose_name_plural": "OTP verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="reset_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reset_tokens",
                to="accounts.passwordresetrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(
                fields=["identifier", "-created_at"],
                name="accounts_pa_identif_cc521d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="accounts_pa_status_c8e36a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["reset_request", "status"],
                name="accounts_ot_reset_r_c31937_idx",
            ),
        ),
    ]
