# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinstructor",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_assignments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_published", "status"], name="courses_cou_is_publ_a9113e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["level", "enrollment_type"], name="courses_cou_level_f804a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["price"], name="courses_cou_price_1fbd18_idx"),
        ),
        migrations.AddConstraint(
            model_name="courseinstructor",
            constraint=models.UniqueConstraint(
                fields=("course", "teacher"), name="unique_course_teacher"
            ),
        ),
    ]
