# Generated by Django 6.0.6 on 2026-08-02 07:48

from django.db import migrations, models


def copy_category_fk_to_m2m(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    through = Course.categories.through
    rows = []
    for course in Course.objects.exclude(category_id=None).iterator():
        rows.append(
            through(course_id=course.pk, coursecategory_id=course.category_id)
        )
    if rows:
        through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="courses.coursecategory"
            ),
        ),
        migrations.RunPython(copy_category_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
    ]
