# Generated by Django 6.0.7 on 2026-07-19 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "enrollment_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("GRADUATED", "Graduated"),
                            ("DROPPED", "Dropped"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("religion", models.CharField(blank=True, max_length=100)),
                ("mother_tongue", models.CharField(blank=True, max_length=100)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("profile_completed", models.BooleanField(default=False)),
                ("permanent_address", models.TextField(blank=True)),
                ("temporary_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Nepal", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("SPOUSE", "Spouse"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        default="GUARDIAN",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=150)),
                ("address", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "guardian",
                "verbose_name_plural": "guardians",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                (
                    "degree_level",
                    models.CharField(
                        blank=True,
                        help_text="Degree or level, e.g. SLC, +2, Bachelor.",
                        max_length=100,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                ("year_from", models.PositiveIntegerField(blank=True, null=True)),
                ("year_to", models.PositiveIntegerField(blank=True, null=True)),
                ("grade_gpa", models.CharField(blank=True, max_length=50)),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="students/academic/"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "academic history",
                "verbose_name_plural": "academic histories",
                "ordering": ["-year_to", "-year_from"],
            },
        ),
        migrations.CreateModel(
            name="StudentActivityLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student activity log",
                "verbose_name_plural": "student activity logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("CITIZENSHIP", "Citizenship"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("TRANSCRIPT", "Transcript"),
                            ("PHOTO", "Photo"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="students/documents/")),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student document",
                "verbose_name_plural": "student documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["status", "student_id"], name="students_st_status_6ab8b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_number"], name="students_st_enrollm_667751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentactivitylog",
            index=models.Index(
                fields=["action", "-created_at"], name="students_st_action_fac464_idx"
            ),
        ),
    ]
