# Generated by Django 6.0.7 on 2026-07-19 11:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "from_path",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("to_path", models.CharField(max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[(301, "301 Permanent"), (302, "302 Temporary")],
                        default=301,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "redirect rule",
                "verbose_name_plural": "redirect rules",
                "ordering": ["from_path"],
            },
        ),
        migrations.CreateModel(
            name="SitemapEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "url_path",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("lastmod", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "sitemap entry",
                "verbose_name_plural": "sitemap entries",
                "ordering": ["-priority", "url_path"],
            },
        ),
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=270)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=100)),
                ("og_description", models.CharField(blank=True, max_length=320)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                (
                    "og_type",
                    models.CharField(blank=True, default="website", max_length=50),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True, default="summary_large_image", max_length=50
                    ),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=100)),
                ("twitter_description", models.CharField(blank=True, max_length=320)),
                (
                    "twitter_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/twitter/"),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        default="index,follow",
                        help_text="e.g. index,follow or noindex,nofollow",
                        max_length=100,
                    ),
                ),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                (
                    "seo_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_indexed", models.BooleanField(db_index=True, default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_metadata",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO metadata",
                "verbose_name_plural": "SEO metadata",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="seo_seometa_slug_33cf32_idx"),
                    models.Index(
                        fields=["is_indexed", "seo_score"],
                        name="seo_seometa_is_inde_d72a10_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"),
                        name="unique_seo_metadata_per_object",
                    )
                ],
            },
        ),
    ]
