# Generated by Django 6.0.6 on 2026-08-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_seometadata_canonical_url_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="seometadata",
            new_name="seo_seometa_canonic_cbf98d_idx",
            old_name="seo_seometa_canonic_idx",
        ),
        migrations.RenameIndex(
            model_name="seometadata",
            new_name="seo_seometa_is_inde_e7ce2d_idx",
            old_name="seo_seometa_indexed_canon_idx",
        ),
    ]
