# Generated by Django 6.0.6 on 2026-08-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0004_sitemapentry_hierarchy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sitemapentry",
            new_name="seo_sitemap_is_publ_73a929_idx",
            old_name="seo_sitemap_pub_idx_idx",
        ),
        migrations.RenameIndex(
            model_name="sitemapentry",
            new_name="seo_sitemap_parent__59320a_idx",
            old_name="seo_sitemap_parent_ord_idx",
        ),
        migrations.RenameIndex(
            model_name="sitemapentry",
            new_name="seo_sitemap_updated_a1508b_idx",
            old_name="seo_sitemap_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="sitemapentry",
            new_name="seo_sitemap_page_ty_0a987d_idx",
            old_name="seo_sitemap_type_pub_idx",
        ),
    ]
